--patch tracking information
--20171207.sql
--end of tracking information
--create STORAGE,INFORMATION_CATEGORY,INFORMATION

CREATE TABLE STORAGE (
	STORAGE_ID int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME varchar(30) NULL,
	PATH varchar(100) NULL,
	LOCATION varchar(100) NULL,
	UPDATE_DATE datetime NULL,
	CONSTRAINT un_STORAGE UNIQUE (NAME)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE INFORMATION_CATEGORY (
	INFORMATION_CATEGORY_ID int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME varchar(50) NULL,
	CHINESE_NAME varchar(50) NULL,
	UPDATE_DATE datetime NULL,
	CONSTRAINT un_INFORMATION_CATEGORY UNIQUE (NAME)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE INFORMATION (
	INFORMATION_ID int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME varchar(200) NULL,
	INFORMATION_CATEGORY_ID int not null,
	SCHOOL_ID int NOT null,
	PROFESSIONAL_ID int null,
	URL varchar(200) NULL,
	CONTENT varchar(2000) NULL,
	YEAR int NULL,
	SET_DATE datetime NOT NULL,
	UPDATE_DATE datetime NULL,
	CONSTRAINT un_INFORMATION UNIQUE (NAME)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;