--patch tracking information
--20171211.sql
--end of tracking information
--create SUPER_GROUP

CREATE TABLE CONFIG (
	CONFIG_ID int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME varchar(50) NULL,
	INPUT varchar(150) NULL,
	DESCRIPTION varchar(200) NULL,
	UPDATE_DATE datetime NULL,
	CONSTRAINT un_CONFIG UNIQUE (NAME)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;