update STUDENT set STATUS = 'NOT_FINISH';

update INFORMATION SET SCHOOL_ID = NULL WHERE SCHOOL_ID = '0';
update INFORMATION SET PROFESSIONAL_ID = NULL WHERE PROFESSIONAL_ID = '0';

update SUPER_GROUP SET SCHOOL_ID = NULL WHERE SCHOOL_ID = '0';
update SUPER_GROUP SET PROFESSIONAL_ID = NULL WHERE PROFESSIONAL_ID = '0';

update INFORMATION SET SCHOOL_ID = NULL WHERE SCHOOL_ID = 0;
update INFORMATION SET PROFESSIONAL_ID = NULL WHERE PROFESSIONAL_ID = 0;
